# Generated by Django 5.2.4 on 2025-09-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='independent_articles',
            field=models.ManyToManyField(blank=True, related_name='independent_journalist_articles', to='news.article'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='independent_newsletters',
            field=models.ManyToManyField(blank=True, related_name='independent_journalist_newsletters', to='news.newsletter'),
        ),
    ]
