# Generated by Django 5.2.4 on 2025-09-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_customuser_independent_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
