from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register,
         name='register'),
    path('login/', views.login_view,
         name='login'),
    path('logout/', views.logout_view,
         name='logout'),
    path('', views.home, name='home'),
    path('journalist/', views.journalist_dashboard,
         name='journalist_dashboard'),
    path('article/create/', views.create_article,
         name='create_article'),
    path('editor/', views.editor_dashboard,
         name='editor_dashboard'),
    path('article/<int:pk>/approve/', views.approve_article,
         name='approve_article'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('article/<int:pk>/edit/', views.edit_article,
         name='edit_article'),
    path('article/<int:pk>/delete/', views.delete_article,
         name='delete_article'),
    path('newsletter/create/', views.create_newsletter,
         name='create_newsletter'),
    path('newsletter/<int:pk>/edit/', views.edit_newsletter,
         name='edit_newsletter'),
    path('newsletter/<int:pk>/delete/', views.delete_newsletter,
         name='delete_newsletter'),
    path('newsletter/<int:pk>/approve/', views.approve_newsletter,
         name='approve_newsletter'),
    # API
    path('api/articles/', views.api_articles,
         name='api_articles'),
    path('api/articles/publisher/<int:pk>/', views.api_list_publisher_articles,
         name='api_list_publisher_articles'),
    path('api/articles/<int:pk>/approve/', views.api_approve_article,
         name='api_approve_article'),
    path('api/subscribe/', views.api_subscribe,
         name='api_subscribe'),
]
